#!/usr/bin/python3

import sys
import os
wc = ''
cat = ''
fileList = []
addons = []
cOption = True
wOption = True
lOption = True
mOption = False
for i in range(1,len(sys.argv)):
	if sys.argv[i][0] != '-':
		fileList.append(sys.argv[i])
	else:
		addons.append(sys.argv[i])	
if len(addons) >= 1:
	cOption = False
	wOption = False
	lOption = False
for options in addons:
	if "l" in options:
		lOption = True
	if "w" in options:
		wOption = True
	if "c" in options:
		cOption = True
if len(fileList) == 0:
	countLines = 0
	countWords = 0
	countBytes = 0
	for line in sys.stdin:
		countLines += 1
		splity = line.split()
		countWords += len(splity)
		countBytes += len(line)
	if lOption:
		print("%3d"%countLines,end='')
	if wOption:
		print(" %3d"%countWords,end='')
	if cOption:
		print(" %3d"%countBytes,end='')
	print('\n')

else:
	for argv in fileList:
		aFile = open(argv,'r')
		countLines = 0
		countWords = 0
		countBytes = 0
		for lines in aFile:
			countLines += 1
			splity = lines.split()
			countWords += len(splity)
			countBytes += len(lines)
		if lOption:
			print("%3d"%countLines,end='')
		if wOption:
			print(" %3d"%countWords,end='')
		if cOption:
			print(" %3d"%countBytes,end='')
		print(' ' + argv)
		aFile.closed


